#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

//STARTS - Code to allow PhpStorm CLI in PhpStorm 10.0.x and Laravel 5.2.x
if (isset($argv[1], $argv[2]) &&
    $argv[1] === 'list' &&
    $argv[2] === '--xml'
) {
    $argv[2]  = '--format=xml';
    $_SERVER['argv'] = $argv;
}
if (isset($argv[1]) && $argv[1] === '-V') {
    die('Symfony version 3.0.0');
}
//ENDS - Code to allow PhpStorm CLI

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
